### PR TITLE
Learning Javacript' promises (by udacity) and my article on Context API

### PR DESCRIPTION
**Pull request by AdithyaBhat17**
Hey, I found out that my repo was one commit behind the base repo but i've implemented the same changes. Sorry for the delay.

### CODE REVIEW

**Comment by KirankumarAmbati** [comment]
Hi @AdithyaBhat17 

Thanks for the PR ! 

There is one correction that needs to be done. Instead of giving link to your article, please can you articulate the concept and write a page with some relevant title Eg. context-api.md

That would be a great help ! Thanks once again !! :smiley:

**Comment by AdithyaBhat17** [comment]
Sure! I'll send another PR later today

**Comment by AdithyaBhat17** [comment]
Hey, I've added ContextAPI.md as suggested.

**Comment by KirankumarAmbati** [comment]
Awesome ! :+1:

**Pull request merged**
